const consent = getConsent();

importScripts('./ngsw-worker.js'); // generated by Angular build process
if (consent.includes('batch')) {
  try {
    importScripts('./batchsdk-shared-worker.js');
  } catch (e) {
    console.error('Failed to load Batch Shared Worker', e);
  }
}

function getConsent() {
  const url = new URL(self.location.href);
  return (url.searchParams.get('consent') || '')
    .split(',')
    .map((s) => s.trim());
}
